version: '2'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    build: .
    image: alexjonas/openvpn
    container_name: openvpn
    ports:
     - "1194:1194/udp"
     - "943:943"
     - "843:443"
    restart: always
    volumes:
     - ./openvpn-data/conf:/etc/openvpn